name: 'Tests (Unit)'

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, ready_for_review]
    paths:
      - '.github/workflows/tests-unit.yml'
      - 'package.json'
      - 'packages/app/**'
      - 'packages/constants/**'
      - 'packages/db/**'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'tsconfig.json'

jobs:
  vitest:
    if: ${{ !github.event.pull_request.draft }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@a15d269cd4658e1107c09f1fabf4cbd7bd1f308a # v4.4.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '24'
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          CYPRESS_INSTALL_BINARY: '0'
      - name: Typecheck
        run: pnpm typecheck
      - name: Unit tests
        run: pnpm test:unit
